applications/persona/urls.py
from django.urls import path
from . import views

app_name="persona_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar-by-area/<shortname>', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('listar-empleados-admin/', views.ListEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado')
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.home .views import IndexView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.departamento.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento

from ckeditor.fields import RichTextField

class Habilidades(models.Model):
    habilidad= models.CharField('Habilidad', max_length=50)

    class meta:
        verbose_name='Habilidad'
        verbose_name_plural='Habilidades Empleados'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad

# Create your models here.
class Empleado(models.Model):
    #Modelo para tabla empleado

    JOB_CHOICES= (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTAS'),
        ('3', '0TRO'),
    )
    first_name=models.CharField('Nombres', max_length=60)
    last_name=models.CharField('Apellidos', max_length=60)
    full_name=models.CharField('Nombres completos', max_length=120, blank=True)
    job=models.CharField('Trabajo',max_length=50, choices=JOB_CHOICES)
    departamento=models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar=models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida =  RichTextField()

    def __str__(self):
        return str(self.id)+'-'+self.first_name+'-'+self.last_name

applications/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):

    class Meta:
        model=Empleado
        fields=(
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)

from .models import Empleado
from .forms import EmpleadoForm

class InicioView(TemplateView):
    template_name='inicio.html'

class ListAllEmpleados(ListView):
    template_name='persona/list_all.html'
    paginate_by=4
    ordering='first_name'
    context_object_name='empleados'
    

    def get_queryset(self):
        palabra_clave=self.request.GET.get("kword", '')
        lista= Empleado.objects.filter(
            first_name__icontains=palabra_clave
        )
        return lista
    
class ListEmpleadosAdmin(ListView):
    template_name='persona/list_empleados.html'
    paginate_by=8
    ordering='first_name'
    context_object_name='empleados'
    model=Empleado

    

class ListByAreaEmpleado(ListView):
    template_name='persona/list_by_area.html'
    context_object_name='empleados'
    
    def get_queryset(self):
        area=self.kwargs['shortname']
        lista= Empleado.objects.filter(
            departamento__short_name=area
        )
        return lista
    
class ListEmpleadosByKword(ListView):
    template_name='persona/by_kword.html'
    context_object_name='empleados'

    def get_queryset(self):
        print('******************')
        palabra_clave=self.request.GET.get("kword", '')
        lista= Empleado.objects.filter(
            first_name=palabra_clave
        )
        print('lista resultado:', lista)
        return lista
    

class ListHabilidadesEmpleado(ListView):
    template_name='persona/habilidades.html'
    context_object_name='habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=8)
        return empleado.habilidades.all()
    
class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo']='Empleado del mes'
        return context

class SuccessView(TemplateView):
    template_name="persona/success.html"

class EmpleadoCreateView(CreateView):
    template_name="persona/add.html"
    model= Empleado
    form_class=EmpleadoForm
    success_url=reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form):
        empleado = form.save(commit=False)
        empleado.full_name=empleado.first_name+' '+empleado.last_name  
        empleado.save()   
        return super(EmpleadoCreateView, self).form_valid(form)

class EmpleadoUpdateView(UpdateView):
    template_name= "persona/update.html"
    model= Empleado
    fields=[
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
    ]

    success_url=reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object=self.get_object()
        print('*******Metodo post*******')
        print('*************************')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        print('***********Metodo form valid**********')
        print('**************************************')
        return super(EmpleadoUpdateView, self).form_valid(form)
    
class EmpleadoDeleteView(DeleteView):
    model=Empleado
    template_name= "persona/delete.html"
    success_url=reverse_lazy('persona_app:empleados_admin')
    

templates/persona/add.html
{% extends 'base.html' %}

{% block title %}
    Registrar empleado
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}
    <div class="container">
        <div class="row">
            <h1>Registrar persona</h1>

        <form method="POST" enctype="multipart/form-data">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Agregar</button>

        </form>
        </div>
    </div>

{% endblock content%}

    
    

templates/persona/by_kword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Lista de Empleados por palabra clave</h1>
    <form tmethod="GET">{% csrf_token %}
        <input ype="text" id="kword" name="kword" placeholder="Ingrese nombre">
        <button type="submit">Buscar</button>
    </form>

    <h3>Lista resultado</h3>
    <ul>
        {% for e in empleados %}
            <li>{{e}}</li>
        {% endfor %}
    </ul>

</body>
</html>

templates/persona/delete.html
{% extends 'base.html' %}

{% block title %}
    Eliminar Empleado
{% endblock title %}

{% block content%}

{% include 'includes/header.html' %}
<div class="container">
    <div class="row">
        <h1>Eliminar</h1>
   
        <form method="POST">{% csrf_token %}

        <p>Confirme que desea eliminar</p>
        <button type="submit">Confirmar</button>
        </form>

    </div>
</div>


{% endblock content %}
   

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
    {{ object.full_name }}
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}
    <div class="container">
        <div class="row">
            <div class="card" style="width: 18rem;">
                {% if empleado.avatar %}
                    <img src="{{ empleado.avatar.url }}" class="card-img-top" alt="...">
                {% else %}

                    <img src="{% static 'img/ribeyro.jpg' %}">
                {% endif %}
                <div class="card-body">
                    <p class="card-text">{{ empleado.first_name }}</p>
                    <p class="card-text">{{ empleado.get_job_display }}</p>
                    <p class="card-text">{{ empleado.departamento.short_name }}</p>
                    <p><span class="label">Habilidades:</span></p>
                    <ul>
                        {% for h in empleado.habilidades.all %}
                            <li>{{ h.habilidad }}</li>
                        {% endfor %}
                    </ul>
                </div>
              </div>  
        </div>
    </div>
    

{% endblock content %}

templates/persona/habilidades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Habilidades del empleado</h1>
    <ul>
        {% for h in habilidades%}
            <li>
               {{ h }} 
            </li>

        {% endfor %}

    </ul>
    
        
</body>
</html>

templates/persona/list_all.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% include 'includes/header.html' %}

<div class="container-fluid principal bg-success row">
    <h3 class="col-12 titulo pt-5">Lista de Empleados</h3>

    <form class="col-12" method="GET">{% csrf_token %}
        Aqui va el buscador y el boton
        <div class="row pt-3">
            <input type="text" class="form-control" id="kword" name="kword">
        </div>
        <div class="row pt-3">
            <button type="submit" class="btn btn-danger" name="button">buscar</button>
        </div>
    </form>
    <div class="col">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">ID</th>
                <th scope="col">NOMBRE</th>
                <th scope="col">APELLIDOS</th>
                <th scope="col">DEPARTAMENTO</th>
                <th scope="col">ACCION</th>
              </tr>
            </thead>
            <tbody>
                {% for e in empleados %}
                    <tr>
                        <th scope="row">{{ e.id }}</th>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento}}</td>
                        <th scope="col"><a class="btn btn-primary" href="{% url 'persona_app:empleado_detail' e.id %}" role="button">Ver</a></th>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>
    <div class="col-12 paginador d-flex justify-content-center">
        {% if is_paginated %}
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                {% endif %}

                {% for pagina in paginator.page_range %}
                
                    {% if pagina == page_obj.number %}
                    <li class="page-item active"><a class="page-link" href="#">{{ pagina}}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{pagina}}">{{ pagina }}</a></li>
                    {% endif %}
                                  
                {% endfor %}
                
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                {% endif %}
                
            </ul>
        </nav>

        {% endif %}
        
    </div>
    
</div>



{% endblock %}

templates/persona/list_by_area.html
{% extends 'base.html' %}

{% block title%}
    Lista empleados por departamento
{% endblock title %}

{% block content %}

    {% include 'includes/header.html' %}

    <div class="container">
        <div class="row">Empleados por Area</div>
        <div class="row">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">NOMBRE</th>
                    <th scope="col">APELLIDOS</th>
                    <th scope="col">DEPARTAMENTO</th>
                    <th scope="col">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                        <tr>
                            <th scope="row">{{ e.id }}</th>
                            <td>{{ e.first_name }}</td>
                            <td>{{ e.last_name }}</td>
                            <td>{{ e.departamento}}</td>
                            <th scope="col"><a class="btn btn-primary" href="{% url 'persona_app:empleado_detail' e.id %}" role="button">Ver</a></th>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            

        </div>
    </div>
 
{% endblock content %}

templates/persona/list_empleados.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% include 'includes/header.html' %}

<div class="container-fluid principal bg-success row">
    <h3 class="col-12 titulo pt-5">Lista de Empleados</h3>

    <div class="col">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">ID</th>
                <th scope="col">NOMBRE</th>
                <th scope="col">APELLIDOS</th>
                <th scope="col">DEPARTAMENTO</th>
                <th scope="col">ACCION</th>
              </tr>
            </thead>
            <tbody>
                {% for e in empleados %}
                    <tr>
                        <th scope="row">{{ e.id }}</th>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento}}</td>
                        <th scope="col"><a class="btn btn-primary" href="{% url 'persona_app:modificar_empleado' e.id %}" role="button">Editar</a></th>
                        <th scope="col"><a class="btn btn-danger" href="{% url 'persona_app:eliminar_empleado' e.id %}" role="button">Eliminar</a></th>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>
    <div class="col-12 paginador d-flex justify-content-center">
        {% if is_paginated %}
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                {% endif %}

                {% for pagina in paginator.page_range %}
                
                    {% if pagina == page_obj.number %}
                    <li class="page-item active"><a class="page-link" href="#">{{ pagina}}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{pagina}}">{{ pagina }}</a></li>
                    {% endif %}
                                  
                {% endfor %}
                
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                {% endif %}
                
            </ul>
        </nav>

        {% endif %}
        
    </div>
    
</div>



{% endblock %}

templates/persona/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Felicitaciones, se guardo correctamente el empleado</h1>
</body>
</html>

templates/persona/update.html
{% extends 'base.html' %}

{% block title%}
    Editar Empleado
{% endblock title %}

{% block content %}

    {% include 'includes/header.html' %}
    <div class="container-fluid row actualizar">
        <div class="col pt-20 mt-20">
            <h1>Actualizar  Datos del Empleado</h1>
        </div>

        <form class="col-12" method="POST">{% csrf_token %}
            <div class="row">
                <label class="form-label col">Nombres:
                    {{ form.first_name }}
                </label>
                
            </div>
            <div class="row">
                <label class="form-label col">Apellidos:
                    {{ form.last_name }}
                </label>
                
            </div>
            <div class="row">
                <label class="form-label col">Trabajo:
                    {{ form.job }}
                </label>
                
            </div>
            <div class="row">
                <label class="form-label col">Area:
                    {{ form.departamento }}
                </label>
                
            </div>
            <div class="row">
                <label class="form-label col">Habilidades:
                    {{ form.habilidades }}
                </label>
                
            </div>
            
            <button class="col-12 d-flex justify-content-center btn btn-primary" type="submit">Actualizar</button>
        </form>

    </div>
    

        

{% endblock content%}
    