applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name="departamento_app"

urlpatterns = [
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
    path('departamento-lista/', views.DepartamentoListView.as_view(), name='departamento_list')
]

applications/persona/urls.py
from django.urls import path
from . import views

app_name="persona_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar-by-area/<shortname>', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('listar-empleados-admin/', views.ListEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado')
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.home .views import IndexView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.departamento.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="encabezado container-fluid row">
    <nav class="navbar navbar-expand-lg fixed-top mt-0 bg-primary col">
        
      <a class="navbar-brand" href="#">Empleados</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'persona_app:empleados_all' %}">Listar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'departamento_app:departamento_list' %}">Departamentos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'persona_app:empleados_admin' %}">Administrar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo Departamento</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Buscar Empleado" aria-label="Search">
          <a class="btn btn-outline-success" href="{% url 'persona_app:empleado_add' %}">Registrar nuevo</a>
        </form>
      </div>
        
    </nav>
</div>
  