applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name="departamento_app"

urlpatterns = [
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
    path('departamento-lista/', views.DepartamentoListView.as_view(), name='departamento_list')
]

applications/persona/urls.py
from django.urls import path
from . import views

app_name="persona_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar-by-area/<shortname>', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('listar-empleados-admin/', views.ListEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado')
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.home .views import IndexView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.departamento.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name=models.CharField('Nombre', max_length=50, blank=True, null=True)
    short_name=models.CharField('Nombre corto', max_length=20, unique=True)
    anulate=models.BooleanField('Anulado', default=False)

        

    def __str__(self):
        return str(self.id) + '-' + self.name+'-' + self.short_name

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre=forms.CharField(max_length=50)
    apellidos=forms.CharField(max_length=50)
    departamento=forms.CharField(max_length=50)
    shortname=forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView

from applications.persona.models import Empleado
from .models import Departamento

from .forms import NewDepartamentoForm

class DepartamentoListView(ListView):
    template_name="departamento/lista.html"
    model=Departamento
    context_object_name='departamentos'

class NewDepartamentoView(FormView):
    template_name='departamento/new_departamento.html'
    form_class= NewDepartamentoForm
    success_url='/'

    def form_valid(self, form):
        print('*****Estamos en el form valid*****')

        depa=Departamento(
            name=form.cleaned_data['departamento'],
            short_name=form.cleaned_data['shortname']
        )
        depa.save()

        nombre=form.cleaned_data['nombre']
        apellido=form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job='1',
            departamento=depa
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}

{% block title %}
    Lista de Departamentos
{% endblock title %}

{% load static %}
{% block content%}

    {% include 'includes/header.html' %}
    <div class="container-fluid">
        
            <div class="row mt-30">
                <h1>Lista Departamentos</h1>
            </div>
            <div class="row">
                <table>
                    <tbody>
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{ departamento.name }}</td>
                            <td>{{ departamento.short_name }}</td>
                            <td>
                                <a class="btn btn-primary" href="{% url 'persona_app:empleados_area' departamento.short_name %}" role="button">Ver Empleados</a> 
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        
    </div>

{% endblock content%}

templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% block title %}
    Registrar Departamento
{% endblock title%}

{% block content %}

{% include 'includes/header.html' %}

<div class="container">
    <div class="row">
        <h1>Registrar Nuevo Departamento</h1>

        <form method="POST">{% csrf_token %}
            <h3>Datos empleado</h3>
            <p>
                {{form.nombre}}
            </p>
            <p>
                {{form.apellidos}}
            </p>
            <h3>Datos del departamento</h3>
            <p>
                {{form.departamento}}
            </p>
            <p>
                {{form.shortname}}
            </p>
            
            <button type="submit">Registrar</button>
        </form>
    </div>
</div>
{% endblock content%}